library(dbscan)

#' @title Cluster models with DBSCAN and selects acceptable and nearly acceptable models
#' @description Cluster models with DBSCAN and selects acceptable and nearly acceptable models based on the stated user performance preferences.
#'
#' @param selected_models Data frame containing selected models from \code{\link{choose_models}}
#' @param preferences List with performance preferences as generated by query_preferences
#'
#' @importFrom dbscan dbscan
#' @return List with the two groups of models "acceptable" and "nearly acceptable"
#' @export
#'
#' @examples
#' cluster_models(selected_models=dataframe(),preferences=list("acc_width"=...,"pre_width"=...,"rec_width"=...,"tra_width"=...))
cluster_models<-function(selected_models,preferences){

  verbose=T
#   demo_preferences<-fromJSON(json_str = '{
#   "acc_width": [0.2],
#   "pre_width": [0.1],
#   "rec_width": [0.12],
#   "tra_width": [0.3]
# }')

  if(verbose){
    print("Selected models include")
    print(head(selected_models))
    }

  if(file.exists("cluster.txt")){
    file.remove("cluster.txt")
  }

  write("Cluster_models() results \n\n",file = "cluster.txt",append = T)


  cluster.exp<-dbscan::dbscan(selected_models[,names(selected_models) %in% c("accuracy","precision","recall","training_time_std")],eps = 0.05,minPts = 3,borderPoints = F)
  selected_models$dbscan<-cluster.exp$cluster-1

  write.csv(selected_models,file = "cluster_dbscan.csv")
  rm(cluster.exp)

  ## Section:Selecting a cluster####



## Section :Setting majority ratio####
majority.ratio<-0.51


## Section :Checking ACC models####
  maxacc<-max(selected_models$accuracy)
  maxrec<-max(selected_models$recall)
  maxpre<-max(selected_models$precision)
  maxtra<-max(selected_models$training_time_std)


  minacc<-maxacc*(1-preferences$acc_width)
  minrec<-maxrec*(1-preferences$rec_width)
  minpre<-maxpre*(1-preferences$pre_width)
  mintra<-maxtra*(1-preferences$tra_width)

#Checking fit inside the acceptable region
print("Checking fit inside the acceptable region")
cluster.fit<-c()
# Loop to compute for all cluster groups found how many models actually fall inside the acceptable range in each of the dimensions.
for (i in 0:max(selected_models$dbscan)) {
  a<-sum(selected_models$accuracy[selected_models$dbscan==i]>minacc)/length(selected_models$accuracy[selected_models$dbscan==i])
  b<-sum(selected_models$precision[selected_models$dbscan==i]>minpre)/length(selected_models$precision[selected_models$dbscan==i])
  c<-sum(selected_models$recall[selected_models$dbscan==i]>minrec)/length(selected_models$recall[selected_models$dbscan==i])
  d<-sum(selected_models$training_time_std[selected_models$dbscan==i]>mintra)/length(selected_models$training_time_std[selected_models$dbscan==i])

  # Saves an average value for acceptable models from the three perspectives for all cluster groups
  print(paste0("Cluster ",i," is ",signif(((a+b+c+d)/4), digits= 4)*100,"% inside the Acceptable region "))
  cluster.fit<-c(cluster.fit,(a+b+c+d)/4)
}
names(cluster.fit)<-0:max(selected_models$dbscan)
# So the selected cluster is...
selected.cluster<-as.numeric(names(cluster.fit[cluster.fit>majority.ratio]))
print("So the selected cluster(s) are...")
print(cluster.fit[cluster.fit>majority.ratio])

# Analysis files for cluster discussion ####
write("Acceptable models \n",file = "cluster.txt",append = T)
write(names(cluster.fit),file = "cluster.txt",append = T)
write(cluster.fit,file = "cluster.txt",append = T)


clusters.acc<-cluster.fit[cluster.fit>majority.ratio]

## Calculate how many clusters are completely inside the region

# How many clusters are completely inside the region over the number of clusters in ACC
inside_acc<-length(clusters.acc[clusters.acc==1])/length(clusters.acc)
acc_distrustpts<-if(inside_acc==1){0}else if(inside_acc>=0.5 & inside_acc<1){1}else if(inside_acc<0.5 & inside_acc>0){2}else if(inside_acc==0){3}


print(paste("Distrust points in ACC region",acc_distrustpts))


## Section :Checking NACC models####
subacc<-maxacc*(1-(preferences$acc_width*2))
subrec<-maxrec*(1-(preferences$rec_width*2))
subpre<-maxpre*(1-(preferences$pre_width*2))
subtra<-maxtra*(1-(preferences$tra_width*2))


print("Checking fit inside the nearly acceptable region")

cluster.misfit<-c()
for (i in 0:max(selected_models$dbscan)) {
  l<-sum((selected_models$accuracy[selected_models$dbscan==i]>subacc)&(selected_models$accuracy[selected_models$dbscan==i]<minacc))/length(selected_models$accuracy[selected_models$dbscan==i])
  m<-sum((selected_models$precision[selected_models$dbscan==i]>subpre)&(selected_models$precision[selected_models$dbscan==i]<minpre))/length(selected_models$precision[selected_models$dbscan==i])
  n<-sum((selected_models$recall[selected_models$dbscan==i]>subrec)&(selected_models$recall[selected_models$dbscan==i]<minrec))/length(selected_models$recall[selected_models$dbscan==i])
  o<-sum((selected_models$training_time_std[selected_models$dbscan==i]>subtra)&(selected_models$training_time_std[selected_models$dbscan==i]<mintra))/length(selected_models$training_time_std[selected_models$dbscan==i])

  print(paste0("Cluster ",i," is ",signif(((l+m+n+o)/4),4)*100,"% inside the Nearly-Acceptable region "))
  cluster.misfit<-c(cluster.misfit,(l+m+n+o)/4)

}
names(cluster.misfit)<-0:max(selected_models$dbscan)
# So the selected cluster is...
selected.anticluster<-as.numeric(names(cluster.misfit[cluster.misfit>majority.ratio]))
print("So the selected cluster(s) are...")
print(cluster.misfit[cluster.misfit>majority.ratio])

# Files for analysis of cluster distribution####
write("\n Nearly acceptable models \n",file = "cluster.txt",append = T)
write(names(cluster.misfit),file = "cluster.txt",append = T)
write(cluster.misfit,file = "cluster.txt",append = T)


clusters.nacc<-cluster.misfit[cluster.misfit>majority.ratio]


if(length(clusters.nacc)>0){
  # If at least one cluster is chosen for NACC group


  ##Calculate how many clusters are completely inside the region

  # How many clusters are completely inside the region over the number of clusters in ACC
  inside_nacc<-length(clusters.nacc[clusters.nacc==1])/length(clusters.nacc)
  nacc_distrustpts<-if(inside_nacc==1){0}else if(inside_nacc>=0.5 & inside_nacc<1){1}else if(inside_nacc<0.5 & inside_nacc>0){2}else if(inside_nacc==0){3}


  print(paste("Distrust points in NACC region",nacc_distrustpts))




  write.csv(selected_models[selected_models$dbscan %in% selected.anticluster , names(selected_models) %in% c("model_name")],row.names = F,file = "cluster_nacc.csv")

  return(list(
    "acceptable_models"=selected_models[selected_models$dbscan %in% selected.cluster , names(selected_models) %in% c("model_name")],
    "nearly_acceptable_models"= selected_models[selected_models$dbscan %in% selected.anticluster , names(selected_models) %in% c("model_name")],
    "distrust"=list("acceptable_models"=acc_distrustpts,
                    "nearly_acceptable_models"=nacc_distrustpts)
  ))
}else{
  if(verbose){
    print("No cluster could be added to the NACC group")
    # IF no cluster could be added to the NACC group
  }

  return(list(
    "acceptable_models"=selected_models[selected_models$dbscan %in% selected.cluster , names(selected_models) %in% c("model_name")],
    "nearly_acceptable_models"= "none",
    "distrust"=list("acceptable_models"=acc_distrustpts,
                    "nearly_acceptable_models"=0) # No points awarded, but considered for the basis
  ))

}


write.csv(selected_models[selected_models$dbscan %in% selected.cluster , names(selected_models) %in% c("model_name")],row.names = F,file = "cluster_acc.csv")





}








